# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -uz_soft@ukr.net
    on_success: never # default: change
    on_failure: always # default: always


env:
  global:
    - CODECOV_TOKEN="4db9ec56-a6ba-41f1-8b82-e94429bb974a"